name: prescription_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_login: '<1.0.0'

  file_picker: ^1.3.4+1
  downloads_path_provider: ^0.1.0
  flutter_downloader: ^1.5.0
  permission_handler: ^5.0.1+1
  rflutter_alert: '^1.0.3'

  amplify_core: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  amplify_analytics_pinpoint: '<1.0.0'
  amplify_storage_s3: '<1.0.0'


flutter:


  uses-material-design: true

